"""add product type slug

Revision ID: 13b162ca472e
Revises: b515ec4038c5
Create Date: 2020-04-17 10:33:09.302557

"""
from alembic import op
import sqlalchemy as sa

from src.repos.product_type import ProductTypeRepo

# revision identifiers, used by Alembic.
revision = '13b162ca472e'
down_revision = 'b515ec4038c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_type', sa.Column('slug', sa.String(length=255), nullable=True))

    product_type_repo = ProductTypeRepo(op.get_bind(), None)
    with product_type_repo.session() as s:
        for product_type in product_type_repo.get_all(session=s):
            product_type.slug = product_type_repo.get_unique_slug(product_type, session=s)
        s.flush()

    op.alter_column('product_type', 'slug', nullable=False)
    op.create_unique_constraint(None, 'product_type', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_type_slug_key', 'product_type', type_='unique')
    op.drop_column('product_type', 'slug')
    # ### end Alembic commands ###
