"""change banners text length

Revision ID: 32f35e063bc3
Revises: 13b162ca472e
Create Date: 2020-05-17 17:36:28.146644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f35e063bc3'
down_revision = '13b162ca472e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banner_text', 'value', type_=sa.UnicodeText(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banner_text', 'value', type_=sa.String(50), nullable=False)
    # ### end Alembic commands ###
