"""add characteristic

Revision ID: 42cbb27e5eaf
Revises: 7909d056635f
Create Date: 2020-10-05 09:45:57.791507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42cbb27e5eaf'
down_revision = '7909d056635f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characteristic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characteristic_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('characteristic_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristic.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characteristic_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('characteristic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Product_type_x_characteristic_value',
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('characteristic_value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_value_id'], ['characteristic_value.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_type.id'], ),
    sa.PrimaryKeyConstraint('product_type_id', 'characteristic_value_id')
    )
    op.create_index(op.f('ix_Product_type_x_characteristic_value_product_type_id'), 'Product_type_x_characteristic_value', ['product_type_id'], unique=False)
    op.create_table('characteristic_value_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('characteristic_value_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_value_id'], ['characteristic_value.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characteristic_value_name')
    op.drop_index(op.f('ix_Product_type_x_characteristic_value_product_type_id'), table_name='Product_type_x_characteristic_value')
    op.drop_table('Product_type_x_characteristic_value')
    op.drop_table('characteristic_value')
    op.drop_table('characteristic_name')
    op.drop_table('characteristic')
    # ### end Alembic commands ###
