"""add promo code

Revision ID: 640128df4c8f
Revises: 32f35e063bc3
Create Date: 2020-05-24 10:39:06.337923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640128df4c8f'
down_revision = '32f35e063bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('value', sa.String(length=60), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disable_on_use', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.add_column('order', sa.Column('promo_code_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'promo_code', ['promo_code_id'], ['id'])

    op.create_table('product_x_promo_code',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_code.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'promo_code_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_promo_code_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'promo_code_id')
    op.drop_table('promo_code')

    op.drop_table('product_x_promo_code')
    # ### end Alembic commands ###
