"""add search indicies

Revision ID: 66e92024b802
Revises: 969a4fac3060
Create Date: 2020-09-05 14:44:34.693057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e92024b802'
down_revision = '969a4fac3060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_category_name_value', 'category_name', ['value'], unique=False)
    op.create_index('ix_product_type_name_value', 'product_type_name', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_type_name_value', table_name='product_type_name')
    op.drop_index('ix_category_name_value', table_name='category_name')
    # ### end Alembic commands ###
