"""add characteristic and features indicies

Revision ID: 7631930b0f1c
Revises: 42cbb27e5eaf
Create Date: 2020-10-08 11:41:36.158437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7631930b0f1c'
down_revision = '42cbb27e5eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Product_type_x_characteristic_value_characteristic_value_id'), 'Product_type_x_characteristic_value', ['characteristic_value_id'], unique=False)
    op.create_index(op.f('ix_category_parent_category_id'), 'category', ['parent_category_id'], unique=False)
    op.create_index(op.f('ix_category_name_category_id'), 'category_name', ['category_id'], unique=False)
    op.create_index(op.f('ix_characteristic_name_characteristic_id'), 'characteristic_name', ['characteristic_id'], unique=False)
    op.create_index(op.f('ix_characteristic_value_characteristic_id'), 'characteristic_value', ['characteristic_id'], unique=False)
    op.create_index(op.f('ix_characteristic_value_name_characteristic_value_id'), 'characteristic_value_name', ['characteristic_value_id'], unique=False)
    op.create_index(op.f('ix_feature_type_name_feature_type_id'), 'feature_type_name', ['feature_type_id'], unique=False)
    op.create_index(op.f('ix_feature_value_feature_type_id'), 'feature_value', ['feature_type_id'], unique=False)
    op.create_index(op.f('ix_feature_value_name_feature_value_id'), 'feature_value_name', ['feature_value_id'], unique=False)
    op.create_index(op.f('ix_product_type_x_feature_type_feature_type_id'), 'product_type_x_feature_type', ['feature_type_id'], unique=False)
    op.create_index(op.f('ix_product_x_feature_value_feature_value_id'), 'product_x_feature_value', ['feature_value_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_x_feature_value_feature_value_id'), table_name='product_x_feature_value')
    op.drop_index(op.f('ix_product_type_x_feature_type_feature_type_id'), table_name='product_type_x_feature_type')
    op.drop_index(op.f('ix_feature_value_name_feature_value_id'), table_name='feature_value_name')
    op.drop_index(op.f('ix_feature_value_feature_type_id'), table_name='feature_value')
    op.drop_index(op.f('ix_feature_type_name_feature_type_id'), table_name='feature_type_name')
    op.drop_index(op.f('ix_characteristic_value_name_characteristic_value_id'), table_name='characteristic_value_name')
    op.drop_index(op.f('ix_characteristic_value_characteristic_id'), table_name='characteristic_value')
    op.drop_index(op.f('ix_characteristic_name_characteristic_id'), table_name='characteristic_name')
    op.drop_index(op.f('ix_category_name_category_id'), table_name='category_name')
    op.drop_index(op.f('ix_category_parent_category_id'), table_name='category')
    op.drop_index(op.f('ix_Product_type_x_characteristic_value_characteristic_value_id'), table_name='Product_type_x_characteristic_value')
    # ### end Alembic commands ###
