"""get back promo code products

Revision ID: 7909d056635f
Revises: d32765046822
Create Date: 2020-09-30 16:27:00.031830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7909d056635f'
down_revision = 'd32765046822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_x_promo_code',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_code.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'promo_code_id')
    )
    op.create_index(op.f('ix_product_x_promo_code_product_id'), 'product_x_promo_code', ['product_id'], unique=False)

    op.drop_column('promo_code', 'products_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_code', sa.Column('products_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_product_x_promo_code_product_id'), table_name='product_x_promo_code')
    op.drop_table('product_x_promo_code')
    # ### end Alembic commands ###
