"""remove sku

Revision ID: 7c8046bd8edd
Revises: 84758aa0ce41
Create Date: 2020-06-15 09:41:10.507295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8046bd8edd'
down_revision = '84758aa0ce41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'sku')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sku', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
