"""make product _ product type _ order _ user _ promo_code  undeletable

Revision ID: 84758aa0ce41
Revises: 640128df4c8f
Create Date: 2020-05-25 10:20:51.379055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84758aa0ce41'
down_revision = '640128df4c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_deleted', sa.Boolean(), nullable=True, default=False))
    op.add_column('product_type', sa.Column('is_deleted', sa.Boolean(), nullable=True, default=False))
    op.add_column('promo_code', sa.Column('is_deleted', sa.Boolean(), nullable=True, default=False))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=True, default=False))
    op.add_column('order', sa.Column('is_deleted', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_deleted')
    op.drop_column('promo_code', 'is_deleted')
    op.drop_column('product_type', 'is_deleted')
    op.drop_column('product', 'is_deleted')
    op.drop_column('order', 'is_deleted')
    # ### end Alembic commands ###
