"""Add promo code amount

Revision ID: 84cafedb61a7
Revises: 85f4718f22e7
Create Date: 2020-07-16 16:29:43.199109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84cafedb61a7'
down_revision = '85f4718f22e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_code', sa.Column('amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo_code', 'amount')
    # ### end Alembic commands ###
