"""add sku & upc

Revision ID: 8f8ec4515212
Revises: c84e9b5ee294
Create Date: 2020-03-10 15:24:58.785389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8ec4515212'
down_revision = 'c84e9b5ee294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('product', sa.Column('upc', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'product', ['upc'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_upc_key', 'product', type_='unique')
    op.drop_column('product', 'upc')
    op.drop_column('product', 'sku')
    # ### end Alembic commands ###
