"""add order indexes

Revision ID: 969a4fac3060
Revises: d9cc3041aba9
Create Date: 2020-08-16 13:25:51.873492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969a4fac3060'
down_revision = 'd9cc3041aba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_order_item_order_id'), 'order_item', ['order_id'], unique=False)
    op.create_index(op.f('ix_product_x_promo_code_product_id'), 'product_x_promo_code', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_x_promo_code_product_id'), table_name='product_x_promo_code')
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    # ### end Alembic commands ###
