"""make product type name longer

Revision ID: 990992000458
Revises: c22c58160968
Create Date: 2020-03-20 15:43:14.761983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990992000458'
down_revision = 'c22c58160968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_type_name', 'value', type_=sa.String(255), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_type_name', 'value', type_=sa.String(50), nullable=False)
    # ### end Alembic commands ###
