"""add banner link text and text offsets

Revision ID: ac5ecce13e16
Revises: 9542d45be0ad
Create Date: 2020-02-26 16:18:59.275497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5ecce13e16'
down_revision = '9542d45be0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner_link_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('banner_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banner_id'], ['banner.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('banner', sa.Column('text_bottom_offset', sa.String(length=10), nullable=True))
    op.add_column('banner', sa.Column('text_left_offset', sa.String(length=10), nullable=True))
    op.add_column('banner', sa.Column('text_right_offset', sa.String(length=10), nullable=True))
    op.add_column('banner', sa.Column('text_top_offset', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'text_top_offset')
    op.drop_column('banner', 'text_right_offset')
    op.drop_column('banner', 'text_left_offset')
    op.drop_column('banner', 'text_bottom_offset')
    op.drop_table('banner_link_text')
    # ### end Alembic commands ###
