"""add category slug

Revision ID: b515ec4038c5
Revises: a22db69ec8a7
Create Date: 2020-04-09 10:42:41.400565

"""
import sqlalchemy as sa
from alembic import op
from slugify import slugify
from sqlalchemy.orm.session import sessionmaker

from src.repos.category import CategoryRepo

# revision identifiers, used by Alembic.
revision = 'b515ec4038c5'
down_revision = 'a22db69ec8a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('slug', sa.String(length=255), nullable=True))

    category_repo = CategoryRepo(op.get_bind())
    with category_repo.session() as s:
        for category in category_repo.get_all(session=s):
            category.slug = category_repo.get_unique_slug(category, session=s)
        s.flush()

    op.alter_column('category', 'slug', nullable=False)
    op.create_unique_constraint(None, 'category', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_slug_key', 'category', type_='unique')
    op.drop_column('category', 'slug')
    # ### end Alembic commands ###
