"""add banners text color

Revision ID: c84e9b5ee294
Revises: ac5ecce13e16
Create Date: 2020-03-06 12:41:15.902677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84e9b5ee294'
down_revision = 'ac5ecce13e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('text_color', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'text_color')
    # ### end Alembic commands ###
