"""add indexes

Revision ID: d9cc3041aba9
Revises: 84cafedb61a7
Create Date: 2020-08-16 12:14:38.083150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9cc3041aba9'
down_revision = '84cafedb61a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_product_type_id'), 'product', ['product_type_id'], unique=False)
    op.create_index(op.f('ix_product_image_product_id'), 'product_image', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_type_description_product_type_id'), 'product_type_description', ['product_type_id'], unique=False)
    op.create_index(op.f('ix_product_type_instagram_link_product_type_id'), 'product_type_instagram_link', ['product_type_id'], unique=False)
    op.create_index(op.f('ix_product_type_name_product_type_id'), 'product_type_name', ['product_type_id'], unique=False)
    op.create_index(op.f('ix_product_type_short_description_product_type_id'), 'product_type_short_description', ['product_type_id'], unique=False)
    op.create_index(op.f('ix_product_type_x_category_product_type_id'), 'product_type_x_category', ['product_type_id'], unique=False)
    op.create_index(op.f('ix_product_type_x_feature_type_product_type_id'), 'product_type_x_feature_type', ['product_type_id'], unique=False)
    op.create_index(op.f('ix_product_x_feature_value_product_id'), 'product_x_feature_value', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_x_feature_value_product_id'), table_name='product_x_feature_value')
    op.drop_index(op.f('ix_product_type_x_feature_type_product_type_id'), table_name='product_type_x_feature_type')
    op.drop_index(op.f('ix_product_type_x_category_product_type_id'), table_name='product_type_x_category')
    op.drop_index(op.f('ix_product_type_short_description_product_type_id'), table_name='product_type_short_description')
    op.drop_index(op.f('ix_product_type_name_product_type_id'), table_name='product_type_name')
    op.drop_index(op.f('ix_product_type_instagram_link_product_type_id'), table_name='product_type_instagram_link')
    op.drop_index(op.f('ix_product_type_description_product_type_id'), table_name='product_type_description')
    op.drop_index(op.f('ix_product_image_product_id'), table_name='product_image')
    op.drop_index(op.f('ix_product_product_type_id'), table_name='product')
    # ### end Alembic commands ###
