"""add parent category field

Revision ID: f31621de7252
Revises: 33466b328f4d
Create Date: 2019-07-07 17:30:47.910294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31621de7252'
down_revision = '33466b328f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('parent_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'category', ['parent_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_parent_category_id_fkey', 'category', type_='foreignkey')
    op.drop_column('category', 'parent_category_id')
    # ### end Alembic commands ###
